### ISSUE TITLE
Why is broccoli-asset-rev in dependencies?

### ISSUE THREAD

**Issue by ef4** [zonkyio/ember-web-app#79]
Why is broccoli-asset-rev in this addon's dependencies, when it ends up getting disabled here:

https://github.com/zonkyio/ember-web-app/blob/d1db17cc2ced8ac9c3ca1253f0fa173fb3740ad3/index.js#L13-L19

Is this just a bug (in which case it probably really goes in devDependencies for the dummy app to use), or am I missing something about what `shouldIncludeChildAddon` does?

**Comment by bobisjan** [comment]
I've looked around and found that this package is currently required here

https://github.com/zonkyio/ember-web-app/blob/d1db17cc2ced8ac9c3ca1253f0fa173fb3740ad3/lib/configure-fingerprint.js#L11

Related commits

- https://github.com/zonkyio/ember-web-app/commit/72876349eb38ef0c8725706d91bd949ff0e7a894
- https://github.com/zonkyio/ember-web-app/commit/5a744bb167a3f4b738f59f2f9d38d1b1a86853f5

My knowledge of the addon's internals are still limited, because I'm maintaining this project for a short period of time, so I need to dig into this part first, before I can tell more. But I'm open for any suggestions about how the relationship between fingerprinting and manifest should be handled.

**Comment by ef4** [comment]
Ah, I see, somehow I missed that one when I searched for it. That seems fine.

I was mostly curious because I'm trying to make sure I really understand all the ways people are using shouldIncludChildAddon, so I don't break compatibility with it. Thanks.
